#+title: Keyb

* Kinesis Adv360 Pro
ZMK Configuration File

fork https://github.com/KinesisCorporation/Adv360-Pro-ZMK
Go modify the `config/adv360.keymap` and save the file.

** Local Builds
Kinesis' ZMK fork recommends building via Docker.
This is acceptable, but slow. Maybe someday I'll setup the environment locally...
For now it's a good reason to do push ups and walk away. Just don't scroll.

This section corresponds to 3 scripts:
- install
  run once
- prepare
  run before re-compiling
- build
  re-compile keyboard layout firmware

*** Install Pre-reqs

#+begin_src shell :tangle install.sh
brew install docker colima lima-additional-guestagents qemu
#+end_src

`lima-additional-guestagents` is x86 support.

*** Prepare
From Apple's ARM silicon: specify x86 target.

#+begin_src shell :tangle prepare.sh
colima start --arch x86_64
#+end_src

If something goes wrong, try:
```
colima stop
colima stop -f
colima delete
```
*** Build
After `colima` is happy -- Just `make` it!

#+begin_src shell :tangle build.sh
make
#+end_src

Takes a while the first time...
and also takes a while for every run... if you're using `colima`.
Tried to speed up by giving colima more resources:
```shell
colima status
colima stop
colima start --cpu 4 --memory 6 --arch x86_84 # cpu, memory persist between starts. arch persists until delete
colima status
```
...didn't seem to speed things up. Still re-building from scratch every time.
...Nevermind! Doesn't seem to be pulling all of the git repos anymore.
Still takes ~5min tho.

** Flashing Firmware
First attempt didn't seem to work. Put in bootloader mode via `Mod`+`Macro1`.

Below are paraphrased instructions from: https://kinesis-ergo.com/wp-content/uploads/Advantage360-Professional-Firmware-Update-Instructions-9.5.24-KB360-PRO.pdf

1. Connect left via USB. Then disconnect and power down the right.
2. Use paperclip to DOUBLE-CLICK the Bootloader Button. The
3. Copy and paste the left firmware file to the “ADV360PRO” drive. The keyboard will flash blue
while installing the file and then disconnect the drive automatically.
5. Turn the left module battery on and disconnect it from the PC. Work quickly and do not allow
the left module to fall asleep while you are updating the right side (you can tap the Fn key on
the left module to reset the 30 second sleep timer).
6. Now connect right side via USB and repeat steps 3 and 4.
7. Once the right side stops flashing blue, hold the Mod key down and confirm both Layer LEDs
light up green to confirm the keyboard is working properly.

*** Troubleshooting
If you run into a state where things are half working...
For your sanity:
1. flash the reset file
2. the default firmware
3. your custom firmware

** Mac OS System Setting Configuration
Mac does some annoying things around key repeats.

*** Key Repeat
#+begin_src shell
antoaenono@antoaenono key-zmk-adv360pro % defaults find keyr
Found 3 keys in domain 'com.apple.Accessibility': {
    KeyRepeatDelay = "1.566666666";
    KeyRepeatEnabled = 0;
    KeyRepeatInterval = 0;
}
Found 3 keys in domain 'Apple Global Domain': {
    InitialKeyRepeat = 0;
    "InitialKeyRepeat_Level_Saved" = 0;
    KeyRepeat = 0;
}
#+end_src

*** Press and Hold
#+begin_src shell
antoaenono@antoaenono key-zmk-adv360pro % defaults find andhold
Found 1 keys in domain 'com.apple.speech.recognition.AppleSpeechRecognition.CustomCommands': {
    "System.PressAndHoldAtItem" =     {
        NashvilleOnlyDisable = 1;
    };
}
Found 1 keys in domain 'org.gnu.Emacs': {
    ApplePressAndHoldEnabled = NO;
}
Found 1 keys in domain 'Apple Global Domain': {
    ApplePressAndHoldEnabled = 0;
}
#+end_src
In the code above, the most important is the last one.
When true, holding down a character brings up the accent menu.

I thought these were getting in the way of `layer-taps` in ZMK, but that turned out to be some kind of firmware corruption issue.

Either way, now none of my keys repeat. This ain't a bad thing.
It encourages me to use the right command, instead of pressing a key many times in a row.
